# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from acl_msgs/SimpleState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SimpleState(genpy.Message):
  _md5sum = "cfc3f29b7f63d9bfdd15aafee94b9fa1"
  _type = "acl_msgs/SimpleState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 segment
float64 x
float64 y
float64 psi
float64 omega
float64 Vx
float64 Vy
float64 psidot
int64 slipping
float64 prev_radius"""
  __slots__ = ['segment','x','y','psi','omega','Vx','Vy','psidot','slipping','prev_radius']
  _slot_types = ['int64','float64','float64','float64','float64','float64','float64','float64','int64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       segment,x,y,psi,omega,Vx,Vy,psidot,slipping,prev_radius

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SimpleState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.segment is None:
        self.segment = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.psi is None:
        self.psi = 0.
      if self.omega is None:
        self.omega = 0.
      if self.Vx is None:
        self.Vx = 0.
      if self.Vy is None:
        self.Vy = 0.
      if self.psidot is None:
        self.psidot = 0.
      if self.slipping is None:
        self.slipping = 0
      if self.prev_radius is None:
        self.prev_radius = 0.
    else:
      self.segment = 0
      self.x = 0.
      self.y = 0.
      self.psi = 0.
      self.omega = 0.
      self.Vx = 0.
      self.Vy = 0.
      self.psidot = 0.
      self.slipping = 0
      self.prev_radius = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q7dqd().pack(_x.segment, _x.x, _x.y, _x.psi, _x.omega, _x.Vx, _x.Vy, _x.psidot, _x.slipping, _x.prev_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.segment, _x.x, _x.y, _x.psi, _x.omega, _x.Vx, _x.Vy, _x.psidot, _x.slipping, _x.prev_radius,) = _get_struct_q7dqd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q7dqd().pack(_x.segment, _x.x, _x.y, _x.psi, _x.omega, _x.Vx, _x.Vy, _x.psidot, _x.slipping, _x.prev_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.segment, _x.x, _x.y, _x.psi, _x.omega, _x.Vx, _x.Vy, _x.psidot, _x.slipping, _x.prev_radius,) = _get_struct_q7dqd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q7dqd = None
def _get_struct_q7dqd():
    global _struct_q7dqd
    if _struct_q7dqd is None:
        _struct_q7dqd = struct.Struct("<q7dqd")
    return _struct_q7dqd
