(cl:in-package acl_msgs-srv)
(cl:export '(N-VAL
          N
          NUMD-VAL
          NUMD
          T-VAL
          T
          H-VAL
          H
          R-VAL
          R
          P0-VAL
          P0
          V0-VAL
          V0
          A0-VAL
          A0
          P1-VAL
          P1
          V1-VAL
          V1
          A1-VAL
          A1
          OBSTACLES-VAL
          OBSTACLES
          TRAJECTORIES-VAL
          TRAJECTORIES
          CONVERGED-VAL
          CONVERGED
))