Header header

float64 JPSa_ms   
float64 JPS_fix_ms  
float64 JPStotal_ms 

int8 JPSa_solved      
int8 JPS_fix_solved   

int8 whole_solved
int8 safe_solved

int8 entered_safe_path

int8 needToComputeSafePath

float64 cvx_decomp_whole_ms  
 

float64 gurobi_whole_ms  
float64 gurobi_whole_ms_mine 
float64 gurobi_whole_trials
float64 gurobi_whole_dt
float64 gurobi_whole_factor


float64 cvx_decomp_safe_ms 

float64 gurobi_safe_ms  
float64 gurobi_safe_ms_mine 
float64 gurobi_safe_trials
float64 gurobi_safe_dt
float64 gurobi_safe_factor

float64 total_replanning_ms

float64 Ja
float64 Ja_inside
float64 Ja_outside

float64 Jb
float64 Jb_inside
float64 Jb_outside
int8 decision 

float64 veloc_norm
float64 total_dist 
float64 angle_deg  

int8 computed_both  

int8 deltaT
int8 indexR
int8 indexH
float64 indexR_percentage
float64 deltaT_percentage
int8 k

