// Generated by gencpp from file acl_msgs/BroadcastTrajectoryFeedback.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_BROADCASTTRAJECTORYFEEDBACK_H
#define ACL_MSGS_MESSAGE_BROADCASTTRAJECTORYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acl_msgs
{
template <class ContainerAllocator>
struct BroadcastTrajectoryFeedback_
{
  typedef BroadcastTrajectoryFeedback_<ContainerAllocator> Type;

  BroadcastTrajectoryFeedback_()
    : percent_complete(0.0)  {
    }
  BroadcastTrajectoryFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef double _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct BroadcastTrajectoryFeedback_

typedef ::acl_msgs::BroadcastTrajectoryFeedback_<std::allocator<void> > BroadcastTrajectoryFeedback;

typedef boost::shared_ptr< ::acl_msgs::BroadcastTrajectoryFeedback > BroadcastTrajectoryFeedbackPtr;
typedef boost::shared_ptr< ::acl_msgs::BroadcastTrajectoryFeedback const> BroadcastTrajectoryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc6abe8bc172f00995b2c3f53015f718";
  }

  static const char* value(const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc6abe8bc172f009ULL;
  static const uint64_t static_value2 = 0x95b2c3f53015f718ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/BroadcastTrajectoryFeedback";
  }

  static const char* value(const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 percent_complete\n"
"\n"
;
  }

  static const char* value(const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BroadcastTrajectoryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::BroadcastTrajectoryFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<double>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_BROADCASTTRAJECTORYFEEDBACK_H
