// Generated by gencpp from file acl_msgs/ClassifierFeature.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_CLASSIFIERFEATURE_H
#define ACL_MSGS_MESSAGE_CLASSIFIERFEATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct ClassifierFeature_
{
  typedef ClassifierFeature_<ContainerAllocator> Type;

  ClassifierFeature_()
    : header()
    , feature_vector()
    , class_name()  {
    }
  ClassifierFeature_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , feature_vector(_alloc)
    , class_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _feature_vector_type;
  _feature_vector_type feature_vector;

   typedef  ::std_msgs::String_<ContainerAllocator>  _class_name_type;
  _class_name_type class_name;





  typedef boost::shared_ptr< ::acl_msgs::ClassifierFeature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::ClassifierFeature_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifierFeature_

typedef ::acl_msgs::ClassifierFeature_<std::allocator<void> > ClassifierFeature;

typedef boost::shared_ptr< ::acl_msgs::ClassifierFeature > ClassifierFeaturePtr;
typedef boost::shared_ptr< ::acl_msgs::ClassifierFeature const> ClassifierFeatureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::ClassifierFeature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::ClassifierFeature_<ContainerAllocator1> & lhs, const ::acl_msgs::ClassifierFeature_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.feature_vector == rhs.feature_vector &&
    lhs.class_name == rhs.class_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::ClassifierFeature_<ContainerAllocator1> & lhs, const ::acl_msgs::ClassifierFeature_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::ClassifierFeature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::ClassifierFeature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::ClassifierFeature_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5d5252854bd1f22959b207699b8c36a";
  }

  static const char* value(const ::acl_msgs::ClassifierFeature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5d5252854bd1f22ULL;
  static const uint64_t static_value2 = 0x959b207699b8c36aULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/ClassifierFeature";
  }

  static const char* value(const ::acl_msgs::ClassifierFeature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] feature_vector\n"
"std_msgs/String class_name\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::acl_msgs::ClassifierFeature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.feature_vector);
      stream.next(m.class_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifierFeature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::ClassifierFeature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::ClassifierFeature_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "feature_vector[]" << std::endl;
    for (size_t i = 0; i < v.feature_vector.size(); ++i)
    {
      s << indent << "  feature_vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.feature_vector[i]);
    }
    s << indent << "class_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.class_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_CLASSIFIERFEATURE_H
