// Generated by gencpp from file acl_msgs/GenPath.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_GENPATH_H
#define ACL_MSGS_MESSAGE_GENPATH_H

#include <ros/service_traits.h>


#include <acl_msgs/GenPathRequest.h>
#include <acl_msgs/GenPathResponse.h>


namespace acl_msgs
{

struct GenPath
{

typedef GenPathRequest Request;
typedef GenPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenPath
} // namespace acl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::acl_msgs::GenPath > {
  static const char* value()
  {
    return "7a3e50543d6de9d6311088a4d374c49c";
  }

  static const char* value(const ::acl_msgs::GenPath&) { return value(); }
};

template<>
struct DataType< ::acl_msgs::GenPath > {
  static const char* value()
  {
    return "acl_msgs/GenPath";
  }

  static const char* value(const ::acl_msgs::GenPath&) { return value(); }
};


// service_traits::MD5Sum< ::acl_msgs::GenPathRequest> should match
// service_traits::MD5Sum< ::acl_msgs::GenPath >
template<>
struct MD5Sum< ::acl_msgs::GenPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::acl_msgs::GenPath >::value();
  }
  static const char* value(const ::acl_msgs::GenPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::acl_msgs::GenPathRequest> should match
// service_traits::DataType< ::acl_msgs::GenPath >
template<>
struct DataType< ::acl_msgs::GenPathRequest>
{
  static const char* value()
  {
    return DataType< ::acl_msgs::GenPath >::value();
  }
  static const char* value(const ::acl_msgs::GenPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::acl_msgs::GenPathResponse> should match
// service_traits::MD5Sum< ::acl_msgs::GenPath >
template<>
struct MD5Sum< ::acl_msgs::GenPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::acl_msgs::GenPath >::value();
  }
  static const char* value(const ::acl_msgs::GenPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::acl_msgs::GenPathResponse> should match
// service_traits::DataType< ::acl_msgs::GenPath >
template<>
struct DataType< ::acl_msgs::GenPathResponse>
{
  static const char* value()
  {
    return DataType< ::acl_msgs::GenPath >::value();
  }
  static const char* value(const ::acl_msgs::GenPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACL_MSGS_MESSAGE_GENPATH_H
