// Generated by gencpp from file acl_msgs/HexCantedAttCmd.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_HEXCANTEDATTCMD_H
#define ACL_MSGS_MESSAGE_HEXCANTEDATTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct HexCantedAttCmd_
{
  typedef HexCantedAttCmd_<ContainerAllocator> Type;

  HexCantedAttCmd_()
    : header()
    , att()
    , rate()
    , Fx(0.0)
    , Fy(0.0)
    , Fz(0.0)
    , att_status(0)  {
    }
  HexCantedAttCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , att(_alloc)
    , rate(_alloc)
    , Fx(0.0)
    , Fy(0.0)
    , Fz(0.0)
    , att_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _att_type;
  _att_type att;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rate_type;
  _rate_type rate;

   typedef double _Fx_type;
  _Fx_type Fx;

   typedef double _Fy_type;
  _Fy_type Fy;

   typedef double _Fz_type;
  _Fz_type Fz;

   typedef int16_t _att_status_type;
  _att_status_type att_status;





  typedef boost::shared_ptr< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> const> ConstPtr;

}; // struct HexCantedAttCmd_

typedef ::acl_msgs::HexCantedAttCmd_<std::allocator<void> > HexCantedAttCmd;

typedef boost::shared_ptr< ::acl_msgs::HexCantedAttCmd > HexCantedAttCmdPtr;
typedef boost::shared_ptr< ::acl_msgs::HexCantedAttCmd const> HexCantedAttCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator1> & lhs, const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.att == rhs.att &&
    lhs.rate == rhs.rate &&
    lhs.Fx == rhs.Fx &&
    lhs.Fy == rhs.Fy &&
    lhs.Fz == rhs.Fz &&
    lhs.att_status == rhs.att_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator1> & lhs, const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9629a5b57e06fabbc9c670074808160";
  }

  static const char* value(const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9629a5b57e06fabULL;
  static const uint64_t static_value2 = 0xbc9c670074808160ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/HexCantedAttCmd";
  }

  static const char* value(const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Quaternion att\n"
"geometry_msgs/Vector3 rate\n"
"float64 Fx\n"
"float64 Fy\n"
"float64 Fz\n"
"int16 att_status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.att);
      stream.next(m.rate);
      stream.next(m.Fx);
      stream.next(m.Fy);
      stream.next(m.Fz);
      stream.next(m.att_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HexCantedAttCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::HexCantedAttCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::HexCantedAttCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "att: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.att);
    s << indent << "rate: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rate);
    s << indent << "Fx: ";
    Printer<double>::stream(s, indent + "  ", v.Fx);
    s << indent << "Fy: ";
    Printer<double>::stream(s, indent + "  ", v.Fy);
    s << indent << "Fz: ";
    Printer<double>::stream(s, indent + "  ", v.Fz);
    s << indent << "att_status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.att_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_HEXCANTEDATTCMD_H
