// Generated by gencpp from file acl_msgs/ImageRect.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_IMAGERECT_H
#define ACL_MSGS_MESSAGE_IMAGERECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acl_msgs
{
template <class ContainerAllocator>
struct ImageRect_
{
  typedef ImageRect_<ContainerAllocator> Type;

  ImageRect_()
    : x(0)
    , y(0)
    , height(0)
    , width(0)
    , score(0.0)
    , class_string()
    , class_id(0)  {
    }
  ImageRect_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , height(0)
    , width(0)
    , score(0.0)
    , class_string(_alloc)
    , class_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;

   typedef float _score_type;
  _score_type score;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_string_type;
  _class_string_type class_string;

   typedef int32_t _class_id_type;
  _class_id_type class_id;





  typedef boost::shared_ptr< ::acl_msgs::ImageRect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::ImageRect_<ContainerAllocator> const> ConstPtr;

}; // struct ImageRect_

typedef ::acl_msgs::ImageRect_<std::allocator<void> > ImageRect;

typedef boost::shared_ptr< ::acl_msgs::ImageRect > ImageRectPtr;
typedef boost::shared_ptr< ::acl_msgs::ImageRect const> ImageRectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::ImageRect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::ImageRect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::ImageRect_<ContainerAllocator1> & lhs, const ::acl_msgs::ImageRect_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.score == rhs.score &&
    lhs.class_string == rhs.class_string &&
    lhs.class_id == rhs.class_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::ImageRect_<ContainerAllocator1> & lhs, const ::acl_msgs::ImageRect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::ImageRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::ImageRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::ImageRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::ImageRect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::ImageRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::ImageRect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cc2dbb204a4d58734e556b0d716a7c5";
  }

  static const char* value(const ::acl_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cc2dbb204a4d587ULL;
  static const uint64_t static_value2 = 0x34e556b0d716a7c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/ImageRect";
  }

  static const char* value(const ::acl_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::ImageRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 height\n"
"int32 width\n"
"float32 score\n"
"string class_string\n"
"int32 class_id\n"
;
  }

  static const char* value(const ::acl_msgs::ImageRect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::ImageRect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.score);
      stream.next(m.class_string);
      stream.next(m.class_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageRect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::ImageRect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::ImageRect_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    s << indent << "class_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_string);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_IMAGERECT_H
