// Generated by gencpp from file acl_msgs/LocalizerTrigger.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_LOCALIZERTRIGGER_H
#define ACL_MSGS_MESSAGE_LOCALIZERTRIGGER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct LocalizerTrigger_
{
  typedef LocalizerTrigger_<ContainerAllocator> Type;

  LocalizerTrigger_()
    : header()
    , class_string()
    , trigger_fov(false)  {
    }
  LocalizerTrigger_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , class_string(_alloc)
    , trigger_fov(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_string_type;
  _class_string_type class_string;

   typedef uint8_t _trigger_fov_type;
  _trigger_fov_type trigger_fov;





  typedef boost::shared_ptr< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizerTrigger_

typedef ::acl_msgs::LocalizerTrigger_<std::allocator<void> > LocalizerTrigger;

typedef boost::shared_ptr< ::acl_msgs::LocalizerTrigger > LocalizerTriggerPtr;
typedef boost::shared_ptr< ::acl_msgs::LocalizerTrigger const> LocalizerTriggerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::LocalizerTrigger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::LocalizerTrigger_<ContainerAllocator1> & lhs, const ::acl_msgs::LocalizerTrigger_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.class_string == rhs.class_string &&
    lhs.trigger_fov == rhs.trigger_fov;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::LocalizerTrigger_<ContainerAllocator1> & lhs, const ::acl_msgs::LocalizerTrigger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47a0bee22db703f6268646b232b82c71";
  }

  static const char* value(const ::acl_msgs::LocalizerTrigger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47a0bee22db703f6ULL;
  static const uint64_t static_value2 = 0x268646b232b82c71ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/LocalizerTrigger";
  }

  static const char* value(const ::acl_msgs::LocalizerTrigger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string class_string\n"
"bool trigger_fov\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::acl_msgs::LocalizerTrigger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.class_string);
      stream.next(m.trigger_fov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizerTrigger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::LocalizerTrigger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::LocalizerTrigger_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "class_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_string);
    s << indent << "trigger_fov: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trigger_fov);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_LOCALIZERTRIGGER_H
