// Generated by gencpp from file acl_msgs/MultiVehWaypointRequest.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_MULTIVEHWAYPOINTREQUEST_H
#define ACL_MSGS_MESSAGE_MULTIVEHWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct MultiVehWaypointRequest_
{
  typedef MultiVehWaypointRequest_<ContainerAllocator> Type;

  MultiVehWaypointRequest_()
    : final_positions()  {
    }
  MultiVehWaypointRequest_(const ContainerAllocator& _alloc)
    : final_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _final_positions_type;
  _final_positions_type final_positions;





  typedef boost::shared_ptr< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVehWaypointRequest_

typedef ::acl_msgs::MultiVehWaypointRequest_<std::allocator<void> > MultiVehWaypointRequest;

typedef boost::shared_ptr< ::acl_msgs::MultiVehWaypointRequest > MultiVehWaypointRequestPtr;
typedef boost::shared_ptr< ::acl_msgs::MultiVehWaypointRequest const> MultiVehWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.final_positions == rhs.final_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28c796eba58ca392bbe3aa6ff3a7809f";
  }

  static const char* value(const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28c796eba58ca392ULL;
  static const uint64_t static_value2 = 0xbbe3aa6ff3a7809fULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/MultiVehWaypointRequest";
  }

  static const char* value(const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] final_positions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVehWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::MultiVehWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "final_positions[]" << std::endl;
    for (size_t i = 0; i < v.final_positions.size(); ++i)
    {
      s << indent << "  final_positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.final_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_MULTIVEHWAYPOINTREQUEST_H
