// Generated by gencpp from file acl_msgs/MultiVehPreComputeResponse.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTERESPONSE_H
#define ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acl_msgs
{
template <class ContainerAllocator>
struct MultiVehPreComputeResponse_
{
  typedef MultiVehPreComputeResponse_<ContainerAllocator> Type;

  MultiVehPreComputeResponse_()
    : converged(false)  {
    }
  MultiVehPreComputeResponse_(const ContainerAllocator& _alloc)
    : converged(false)  {
  (void)_alloc;
    }



   typedef uint8_t _converged_type;
  _converged_type converged;





  typedef boost::shared_ptr< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVehPreComputeResponse_

typedef ::acl_msgs::MultiVehPreComputeResponse_<std::allocator<void> > MultiVehPreComputeResponse;

typedef boost::shared_ptr< ::acl_msgs::MultiVehPreComputeResponse > MultiVehPreComputeResponsePtr;
typedef boost::shared_ptr< ::acl_msgs::MultiVehPreComputeResponse const> MultiVehPreComputeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.converged == rhs.converged;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a66f7ff8742366f455ff1c2cabe6fdef";
  }

  static const char* value(const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa66f7ff8742366f4ULL;
  static const uint64_t static_value2 = 0x55ff1c2cabe6fdefULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/MultiVehPreComputeResponse";
  }

  static const char* value(const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool converged\n"
;
  }

  static const char* value(const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.converged);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVehPreComputeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::MultiVehPreComputeResponse_<ContainerAllocator>& v)
  {
    s << indent << "converged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.converged);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTERESPONSE_H
