// Generated by gencpp from file acl_msgs/MultiVehTakeoffLandResponse.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_MULTIVEHTAKEOFFLANDRESPONSE_H
#define ACL_MSGS_MESSAGE_MULTIVEHTAKEOFFLANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acl_msgs
{
template <class ContainerAllocator>
struct MultiVehTakeoffLandResponse_
{
  typedef MultiVehTakeoffLandResponse_<ContainerAllocator> Type;

  MultiVehTakeoffLandResponse_()
    : done(false)  {
    }
  MultiVehTakeoffLandResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiVehTakeoffLandResponse_

typedef ::acl_msgs::MultiVehTakeoffLandResponse_<std::allocator<void> > MultiVehTakeoffLandResponse;

typedef boost::shared_ptr< ::acl_msgs::MultiVehTakeoffLandResponse > MultiVehTakeoffLandResponsePtr;
typedef boost::shared_ptr< ::acl_msgs::MultiVehTakeoffLandResponse const> MultiVehTakeoffLandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/MultiVehTakeoffLandResponse";
  }

  static const char* value(const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
;
  }

  static const char* value(const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiVehTakeoffLandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::MultiVehTakeoffLandResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_MULTIVEHTAKEOFFLANDRESPONSE_H
