// Generated by gencpp from file acl_msgs/MultiVehPreCompute.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTE_H
#define ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTE_H

#include <ros/service_traits.h>


#include <acl_msgs/MultiVehPreComputeRequest.h>
#include <acl_msgs/MultiVehPreComputeResponse.h>


namespace acl_msgs
{

struct MultiVehPreCompute
{

typedef MultiVehPreComputeRequest Request;
typedef MultiVehPreComputeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiVehPreCompute
} // namespace acl_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::acl_msgs::MultiVehPreCompute > {
  static const char* value()
  {
    return "f732d1c522c27f0f4a1daaa555df5861";
  }

  static const char* value(const ::acl_msgs::MultiVehPreCompute&) { return value(); }
};

template<>
struct DataType< ::acl_msgs::MultiVehPreCompute > {
  static const char* value()
  {
    return "acl_msgs/MultiVehPreCompute";
  }

  static const char* value(const ::acl_msgs::MultiVehPreCompute&) { return value(); }
};


// service_traits::MD5Sum< ::acl_msgs::MultiVehPreComputeRequest> should match
// service_traits::MD5Sum< ::acl_msgs::MultiVehPreCompute >
template<>
struct MD5Sum< ::acl_msgs::MultiVehPreComputeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::acl_msgs::MultiVehPreCompute >::value();
  }
  static const char* value(const ::acl_msgs::MultiVehPreComputeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::acl_msgs::MultiVehPreComputeRequest> should match
// service_traits::DataType< ::acl_msgs::MultiVehPreCompute >
template<>
struct DataType< ::acl_msgs::MultiVehPreComputeRequest>
{
  static const char* value()
  {
    return DataType< ::acl_msgs::MultiVehPreCompute >::value();
  }
  static const char* value(const ::acl_msgs::MultiVehPreComputeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::acl_msgs::MultiVehPreComputeResponse> should match
// service_traits::MD5Sum< ::acl_msgs::MultiVehPreCompute >
template<>
struct MD5Sum< ::acl_msgs::MultiVehPreComputeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::acl_msgs::MultiVehPreCompute >::value();
  }
  static const char* value(const ::acl_msgs::MultiVehPreComputeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::acl_msgs::MultiVehPreComputeResponse> should match
// service_traits::DataType< ::acl_msgs::MultiVehPreCompute >
template<>
struct DataType< ::acl_msgs::MultiVehPreComputeResponse>
{
  static const char* value()
  {
    return DataType< ::acl_msgs::MultiVehPreCompute >::value();
  }
  static const char* value(const ::acl_msgs::MultiVehPreComputeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACL_MSGS_MESSAGE_MULTIVEHPRECOMPUTE_H
