// Generated by gencpp from file acl_msgs/OLcmdResponse.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_OLCMDRESPONSE_H
#define ACL_MSGS_MESSAGE_OLCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acl_msgs
{
template <class ContainerAllocator>
struct OLcmdResponse_
{
  typedef OLcmdResponse_<ContainerAllocator> Type;

  OLcmdResponse_()
    : finish(false)  {
    }
  OLcmdResponse_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::acl_msgs::OLcmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::OLcmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OLcmdResponse_

typedef ::acl_msgs::OLcmdResponse_<std::allocator<void> > OLcmdResponse;

typedef boost::shared_ptr< ::acl_msgs::OLcmdResponse > OLcmdResponsePtr;
typedef boost::shared_ptr< ::acl_msgs::OLcmdResponse const> OLcmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::OLcmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::OLcmdResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::OLcmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::OLcmdResponse_<ContainerAllocator1> & lhs, const ::acl_msgs::OLcmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::OLcmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::OLcmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::OLcmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::acl_msgs::OLcmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/OLcmdResponse";
  }

  static const char* value(const ::acl_msgs::OLcmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n"
;
  }

  static const char* value(const ::acl_msgs::OLcmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OLcmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::OLcmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::OLcmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_OLCMDRESPONSE_H
