// Generated by gencpp from file acl_msgs/QuadHealth.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_QUADHEALTH_H
#define ACL_MSGS_MESSAGE_QUADHEALTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct QuadHealth_
{
  typedef QuadHealth_<ContainerAllocator> Type;

  QuadHealth_()
    : header()
    , time_since_boot(0.0)
    , dropped_packets(0)
    , received_seq(0)
    , voltage(0.0)
    , current()
    , temperature()  {
      current.assign(0.0);

      temperature.assign(0.0);
  }
  QuadHealth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_since_boot(0.0)
    , dropped_packets(0)
    , received_seq(0)
    , voltage(0.0)
    , current()
    , temperature()  {
  (void)_alloc;
      current.assign(0.0);

      temperature.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _time_since_boot_type;
  _time_since_boot_type time_since_boot;

   typedef int64_t _dropped_packets_type;
  _dropped_packets_type dropped_packets;

   typedef uint8_t _received_seq_type;
  _received_seq_type received_seq;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef boost::array<double, 4>  _current_type;
  _current_type current;

   typedef boost::array<double, 4>  _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::acl_msgs::QuadHealth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::QuadHealth_<ContainerAllocator> const> ConstPtr;

}; // struct QuadHealth_

typedef ::acl_msgs::QuadHealth_<std::allocator<void> > QuadHealth;

typedef boost::shared_ptr< ::acl_msgs::QuadHealth > QuadHealthPtr;
typedef boost::shared_ptr< ::acl_msgs::QuadHealth const> QuadHealthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::QuadHealth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::QuadHealth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::QuadHealth_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadHealth_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time_since_boot == rhs.time_since_boot &&
    lhs.dropped_packets == rhs.dropped_packets &&
    lhs.received_seq == rhs.received_seq &&
    lhs.voltage == rhs.voltage &&
    lhs.current == rhs.current &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::QuadHealth_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadHealth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadHealth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadHealth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadHealth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadHealth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::QuadHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343728cd67e960654d49bfc9f80c1b8b";
  }

  static const char* value(const ::acl_msgs::QuadHealth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343728cd67e96065ULL;
  static const uint64_t static_value2 = 0x4d49bfc9f80c1b8bULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::QuadHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/QuadHealth";
  }

  static const char* value(const ::acl_msgs::QuadHealth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::QuadHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 time_since_boot\n"
"int64 dropped_packets\n"
"uint8 received_seq\n"
"float64 voltage\n"
"float64[4] current\n"
"float64[4] temperature\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::acl_msgs::QuadHealth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::QuadHealth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_since_boot);
      stream.next(m.dropped_packets);
      stream.next(m.received_seq);
      stream.next(m.voltage);
      stream.next(m.current);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadHealth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::QuadHealth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::QuadHealth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_since_boot: ";
    Printer<double>::stream(s, indent + "  ", v.time_since_boot);
    s << indent << "dropped_packets: ";
    Printer<int64_t>::stream(s, indent + "  ", v.dropped_packets);
    s << indent << "received_seq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_seq);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "temperature[]" << std::endl;
    for (size_t i = 0; i < v.temperature.size(); ++i)
    {
      s << indent << "  temperature[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.temperature[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_QUADHEALTH_H
