// Generated by gencpp from file acl_msgs/QuadRawSensors.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_QUADRAWSENSORS_H
#define ACL_MSGS_MESSAGE_QUADRAWSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct QuadRawSensors_
{
  typedef QuadRawSensors_<ContainerAllocator> Type;

  QuadRawSensors_()
    : header()
    , received_seq(0)
    , gyro()
    , accel()
    , accel_f()
    , mag()
    , pressure(0.0)  {
    }
  QuadRawSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , received_seq(0)
    , gyro(_alloc)
    , accel(_alloc)
    , accel_f(_alloc)
    , mag(_alloc)
    , pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _received_seq_type;
  _received_seq_type received_seq;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gyro_type;
  _gyro_type gyro;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accel_type;
  _accel_type accel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accel_f_type;
  _accel_f_type accel_f;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _mag_type;
  _mag_type mag;

   typedef double _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::acl_msgs::QuadRawSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::QuadRawSensors_<ContainerAllocator> const> ConstPtr;

}; // struct QuadRawSensors_

typedef ::acl_msgs::QuadRawSensors_<std::allocator<void> > QuadRawSensors;

typedef boost::shared_ptr< ::acl_msgs::QuadRawSensors > QuadRawSensorsPtr;
typedef boost::shared_ptr< ::acl_msgs::QuadRawSensors const> QuadRawSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::QuadRawSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::QuadRawSensors_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadRawSensors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.received_seq == rhs.received_seq &&
    lhs.gyro == rhs.gyro &&
    lhs.accel == rhs.accel &&
    lhs.accel_f == rhs.accel_f &&
    lhs.mag == rhs.mag &&
    lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::QuadRawSensors_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadRawSensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadRawSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadRawSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadRawSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "576df60f63a0e261ad4b0bad7d28d5b7";
  }

  static const char* value(const ::acl_msgs::QuadRawSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x576df60f63a0e261ULL;
  static const uint64_t static_value2 = 0xad4b0bad7d28d5b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/QuadRawSensors";
  }

  static const char* value(const ::acl_msgs::QuadRawSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 received_seq\n"
"geometry_msgs/Vector3 gyro\n"
"geometry_msgs/Vector3 accel\n"
"geometry_msgs/Vector3 accel_f\n"
"geometry_msgs/Vector3 mag\n"
"float64 pressure\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acl_msgs::QuadRawSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.received_seq);
      stream.next(m.gyro);
      stream.next(m.accel);
      stream.next(m.accel_f);
      stream.next(m.mag);
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadRawSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::QuadRawSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::QuadRawSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "received_seq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_seq);
    s << indent << "gyro: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gyro);
    s << indent << "accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accel);
    s << indent << "accel_f: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accel_f);
    s << indent << "mag: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.mag);
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_QUADRAWSENSORS_H
