// Generated by gencpp from file acl_msgs/QuadAHRS.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_QUADAHRS_H
#define ACL_MSGS_MESSAGE_QUADAHRS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct QuadAHRS_
{
  typedef QuadAHRS_<ContainerAllocator> Type;

  QuadAHRS_()
    : header()
    , att()
    , att_meas()
    , rpy()
    , rpy_meas()  {
    }
  QuadAHRS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , att(_alloc)
    , att_meas(_alloc)
    , rpy(_alloc)
    , rpy_meas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _att_type;
  _att_type att;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _att_meas_type;
  _att_meas_type att_meas;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_meas_type;
  _rpy_meas_type rpy_meas;





  typedef boost::shared_ptr< ::acl_msgs::QuadAHRS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::QuadAHRS_<ContainerAllocator> const> ConstPtr;

}; // struct QuadAHRS_

typedef ::acl_msgs::QuadAHRS_<std::allocator<void> > QuadAHRS;

typedef boost::shared_ptr< ::acl_msgs::QuadAHRS > QuadAHRSPtr;
typedef boost::shared_ptr< ::acl_msgs::QuadAHRS const> QuadAHRSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::QuadAHRS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::QuadAHRS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::QuadAHRS_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadAHRS_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.att == rhs.att &&
    lhs.att_meas == rhs.att_meas &&
    lhs.rpy == rhs.rpy &&
    lhs.rpy_meas == rhs.rpy_meas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::QuadAHRS_<ContainerAllocator1> & lhs, const ::acl_msgs::QuadAHRS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::QuadAHRS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::QuadAHRS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::QuadAHRS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f4a3386f9afc8a5354d3ad861314b66";
  }

  static const char* value(const ::acl_msgs::QuadAHRS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f4a3386f9afc8a5ULL;
  static const uint64_t static_value2 = 0x354d3ad861314b66ULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/QuadAHRS";
  }

  static const char* value(const ::acl_msgs::QuadAHRS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Quaternion att\n"
"geometry_msgs/Quaternion att_meas\n"
"geometry_msgs/Vector3 rpy\n"
"geometry_msgs/Vector3 rpy_meas\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acl_msgs::QuadAHRS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.att);
      stream.next(m.att_meas);
      stream.next(m.rpy);
      stream.next(m.rpy_meas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadAHRS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::QuadAHRS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::QuadAHRS_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "att: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.att);
    s << indent << "att_meas: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.att_meas);
    s << indent << "rpy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
    s << indent << "rpy_meas: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_meas);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_QUADAHRS_H
