// Generated by gencpp from file acl_msgs/Return2StartActionGoal.msg
// DO NOT EDIT!


#ifndef ACL_MSGS_MESSAGE_RETURN2STARTACTIONGOAL_H
#define ACL_MSGS_MESSAGE_RETURN2STARTACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <acl_msgs/Return2StartGoal.h>

namespace acl_msgs
{
template <class ContainerAllocator>
struct Return2StartActionGoal_
{
  typedef Return2StartActionGoal_<ContainerAllocator> Type;

  Return2StartActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  Return2StartActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::acl_msgs::Return2StartGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct Return2StartActionGoal_

typedef ::acl_msgs::Return2StartActionGoal_<std::allocator<void> > Return2StartActionGoal;

typedef boost::shared_ptr< ::acl_msgs::Return2StartActionGoal > Return2StartActionGoalPtr;
typedef boost::shared_ptr< ::acl_msgs::Return2StartActionGoal const> Return2StartActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator1> & lhs, const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator1> & lhs, const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da899830dd7dc0a92fd7f8f1b8d78d8d";
  }

  static const char* value(const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda899830dd7dc0a9ULL;
  static const uint64_t static_value2 = 0x2fd7f8f1b8d78d8dULL;
};

template<class ContainerAllocator>
struct DataType< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acl_msgs/Return2StartActionGoal";
  }

  static const char* value(const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"Return2StartGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: acl_msgs/Return2StartGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"float64 r\n"
"float64 v\n"
;
  }

  static const char* value(const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Return2StartActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acl_msgs::Return2StartActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acl_msgs::Return2StartActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::acl_msgs::Return2StartGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACL_MSGS_MESSAGE_RETURN2STARTACTIONGOAL_H
