(cl:in-package acl_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          JPSA_MS-VAL
          JPSA_MS
          JPS_FIX_MS-VAL
          JPS_FIX_MS
          JPSTOTAL_MS-VAL
          JPSTOTAL_MS
          JPSA_SOLVED-VAL
          JPSA_SOLVED
          JPS_FIX_SOLVED-VAL
          JPS_FIX_SOLVED
          WHOLE_SOLVED-VAL
          WHOLE_SOLVED
          SAFE_SOLVED-VAL
          SAFE_SOLVED
          ENTERED_SAFE_PATH-VAL
          ENTERED_SAFE_PATH
          NEEDTOCOMPUTESAFEPATH-VAL
          NEEDTOCOMPUTESAFEPATH
          CVX_DECOMP_WHOLE_MS-VAL
          CVX_DECOMP_WHOLE_MS
          GUROBI_WHOLE_MS-VAL
          GUROBI_WHOLE_MS
          GUROBI_WHOLE_MS_MINE-VAL
          GUROBI_WHOLE_MS_MINE
          GUROBI_WHOLE_TRIALS-VAL
          GUROBI_WHOLE_TRIALS
          GUROBI_WHOLE_DT-VAL
          GUROBI_WHOLE_DT
          GUROBI_WHOLE_FACTOR-VAL
          GUROBI_WHOLE_FACTOR
          CVX_DECOMP_SAFE_MS-VAL
          CVX_DECOMP_SAFE_MS
          GUROBI_SAFE_MS-VAL
          GUROBI_SAFE_MS
          GUROBI_SAFE_MS_MINE-VAL
          GUROBI_SAFE_MS_MINE
          GUROBI_SAFE_TRIALS-VAL
          GUROBI_SAFE_TRIALS
          GUROBI_SAFE_DT-VAL
          GUROBI_SAFE_DT
          GUROBI_SAFE_FACTOR-VAL
          GUROBI_SAFE_FACTOR
          TOTAL_REPLANNING_MS-VAL
          TOTAL_REPLANNING_MS
          JA-VAL
          JA
          JA_INSIDE-VAL
          JA_INSIDE
          JA_OUTSIDE-VAL
          JA_OUTSIDE
          JB-VAL
          JB
          JB_INSIDE-VAL
          JB_INSIDE
          JB_OUTSIDE-VAL
          JB_OUTSIDE
          DECISION-VAL
          DECISION
          VELOC_NORM-VAL
          VELOC_NORM
          TOTAL_DIST-VAL
          TOTAL_DIST
          ANGLE_DEG-VAL
          ANGLE_DEG
          COMPUTED_BOTH-VAL
          COMPUTED_BOTH
          DELTAT-VAL
          DELTAT
          INDEXR-VAL
          INDEXR
          INDEXH-VAL
          INDEXH
          INDEXR_PERCENTAGE-VAL
          INDEXR_PERCENTAGE
          DELTAT_PERCENTAGE-VAL
          DELTAT_PERCENTAGE
          K-VAL
          K
))