(cl:in-package acl_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSE-VAL
          POSE
          VX-VAL
          VX
          VY-VAL
          VY
          R-VAL
          R
          OMEGAF-VAL
          OMEGAF
          OMEGAR-VAL
          OMEGAR
          THROTTLE-VAL
          THROTTLE
          TURN-VAL
          TURN
          X_CENTER-VAL
          X_CENTER
          Y_CENTER-VAL
          Y_CENTER
          R-VAL
          R
          F_FLX-VAL
          F_FLX
          F_FLY-VAL
          F_FLY
          F_FLZ-VAL
          F_FLZ
          F_FRX-VAL
          F_FRX
          F_FRY-VAL
          F_FRY
          F_FRZ-VAL
          F_FRZ
          F_RLX-VAL
          F_RLX
          F_RLY-VAL
          F_RLY
          F_RLZ-VAL
          F_RLZ
          F_RRX-VAL
          F_RRX
          F_RRY-VAL
          F_RRY
          F_RRZ-VAL
          F_RRZ
          AX-VAL
          AX
          AY-VAL
          AY
))