(cl:in-package acl_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSE-VAL
          POSE
          POSE_ACTUAL-VAL
          POSE_ACTUAL
          TWIST-VAL
          TWIST
          TWIST_ACTUAL-VAL
          TWIST_ACTUAL
          RPY-VAL
          RPY
          RPY_ACTUAL-VAL
          RPY_ACTUAL
          ACCEL-VAL
          ACCEL
          ACCEL_FB-VAL
          ACCEL_FB
          JERK-VAL
          JERK
          JERK_FB-VAL
          JERK_FB
          POS_INTEGRATOR-VAL
          POS_INTEGRATOR
          VEL_INTEGRATOR-VAL
          VEL_INTEGRATOR
          S-VAL
          S
          C-VAL
          C
          PHI-VAL
          PHI
          PHI_M-VAL
          PHI_M
          U-VAL
          U
          A-VAL
          A
          B-VAL
          B
          YAW-VAL
          YAW
          F_TOTAL-VAL
          F_TOTAL
          THROTTLE-VAL
          THROTTLE
          ATT_STATUS-VAL
          ATT_STATUS
          VICON_TIME-VAL
          VICON_TIME
))