; Auto-generated. Do not edit!


(cl:in-package acl_msgs-msg)


;//! \htmlinclude Return2StartFeedback.msg.html

(cl:defclass <Return2StartFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass Return2StartFeedback (<Return2StartFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Return2StartFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Return2StartFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acl_msgs-msg:<Return2StartFeedback> is deprecated: use acl_msgs-msg:Return2StartFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <Return2StartFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acl_msgs-msg:percent_complete-val is deprecated.  Use acl_msgs-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Return2StartFeedback>) ostream)
  "Serializes a message object of type '<Return2StartFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Return2StartFeedback>) istream)
  "Deserializes a message object of type '<Return2StartFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Return2StartFeedback>)))
  "Returns string type for a message object of type '<Return2StartFeedback>"
  "acl_msgs/Return2StartFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Return2StartFeedback)))
  "Returns string type for a message object of type 'Return2StartFeedback"
  "acl_msgs/Return2StartFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Return2StartFeedback>)))
  "Returns md5sum for a message object of type '<Return2StartFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Return2StartFeedback)))
  "Returns md5sum for a message object of type 'Return2StartFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Return2StartFeedback>)))
  "Returns full string definition for message of type '<Return2StartFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Return2StartFeedback)))
  "Returns full string definition for message of type 'Return2StartFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Return2StartFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Return2StartFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Return2StartFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
