; Auto-generated. Do not edit!


(cl:in-package acl_msgs-msg)


;//! \htmlinclude Return2StartResult.msg.html

(cl:defclass <Return2StartResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass Return2StartResult (<Return2StartResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Return2StartResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Return2StartResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acl_msgs-msg:<Return2StartResult> is deprecated: use acl_msgs-msg:Return2StartResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <Return2StartResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acl_msgs-msg:success-val is deprecated.  Use acl_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Return2StartResult>) ostream)
  "Serializes a message object of type '<Return2StartResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Return2StartResult>) istream)
  "Deserializes a message object of type '<Return2StartResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Return2StartResult>)))
  "Returns string type for a message object of type '<Return2StartResult>"
  "acl_msgs/Return2StartResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Return2StartResult)))
  "Returns string type for a message object of type 'Return2StartResult"
  "acl_msgs/Return2StartResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Return2StartResult>)))
  "Returns md5sum for a message object of type '<Return2StartResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Return2StartResult)))
  "Returns md5sum for a message object of type 'Return2StartResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Return2StartResult>)))
  "Returns full string definition for message of type '<Return2StartResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Return2StartResult)))
  "Returns full string definition for message of type 'Return2StartResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Return2StartResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Return2StartResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Return2StartResult
    (cl:cons ':success (success msg))
))
